trigger:
  branches:
    include:
      - main

pool: 'pr114-linux'

variables:
  BuildConfiguration: 'Release'

stages:
  - stage: API
    jobs:
      - job: API
        displayName: 'API'
        steps:
          - checkout: self
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              workingDirectory: 'api'
              useGlobalJson: true
          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              workingDirectory: 'src/api'
              projects: '**/*.sln'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              workingDirectory: 'src/api'
              projects: '**/*.sln'
              arguments: '--configuration $(BuildConfiguration)'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              workingDirectory: 'src/api'
              projects: '**/*tests.csproj'
              arguments: '--configuration $(BuildConfiguration)'