trigger:
  branches:
    include:
      - main

pool: 'pr114-linux'

variables:
  BuildConfiguration: 'Release'

stages:
  - stage: API
    jobs:
      - job: API
        displayName: 'API'
        steps:
          - checkout: self
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              workingDirectory: 'src/api'
              useGlobalJson: true
          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              workingDirectory: 'src/api'
              projects: '**/*.sln'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              workingDirectory: 'src/api'
              projects: '**/*.sln'
              arguments: '--configuration $(BuildConfiguration)'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              workingDirectory: 'src/api'
              projects: '**/*tests.csproj'
              arguments: '--configuration $(BuildConfiguration)'
  - stage: Web
    jobs:
      - job: Web
        displayName: 'Web'
        steps:
          - checkout: self
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'
          - script: |
              npm ci
              npm run build
            workingDirectory: 'src/web/btweb'
            displayName: 'npm install and build'
  - stage: Docker-API
    jobs:
      - job: Docker-API
        displayName: 'Docker API'
        steps:
          - checkout: self
          - task: Docker@2
            inputs:
              command: 'build'
              Dockerfile: 'src/api/api/Dockerfile'
              tags: '$(Build.BuildId)'