version: '3.8'

services:
  api: 
    image: docker.io/local/capp/api
    deploy:
      replicas: 5
    networks:
      - api-network
  ingress:
    image: nginx:alpine
    deploy:
      replicas: 1
    volumes:
      - ./rp/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - api-network

networks:
  api-network: