using 'app.bicep'

param location = 'switzerlandnorth'
param env = 'dev'
param dashedNameSuffix = 'capplab-${env}-01'
param caeEnvName = 'cae-capplab-dev-01'
param acrName = 'acrcapplabgbodev01'
param uaidName = 'id-capp-capplab-dev-01'
param containerImageRepository = 'capplab'
param containerImageTag = '1.12'
param secretName = 'test001'
param vaultName = 'kv-capplabgbodev01'
