using 'app.bicep'

param location = 'switzerlandnorth'
param env = 'dev'
param dashedNameSuffix = 'capplab-${env}-01'
param blockNameSuffix = 'capplabgbo${env}01'
param caeEnvName = ''
param acrName = ''
param uaidName = ''
param containerImageRepository = ' '
param containerImageTag = 'latest'
